### ISSUE TITLE
若要修改某个日期数字下的背景，该如果做

### ISSUE THREAD

**Issue by linfeizheng** [codbking/CalendarExaple#1]
我需要根据每个日期的任务完成状态修改数字下的背景，请教一下方法，看代码只看到点击事件并没有看到背景切换，谢谢

**Comment by codbking** [comment]
试试CalendarDateView.setAdapter()的方法，CaledarAdapter有个getView，这个返回过来的view就是数字的view，你可以在这个view进行自定义

**Comment by wangyuan0217** [comment]
可是没有notify啊
